try:
    print(x)
except:
    print("something went wrong")
finally:
    print("the try expect is finished")

